apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PREFIX}adminer
  namespace: doe25-group-13
  labels:
    app: ${PREFIX}adminer
    nis2.eu/entity-classification: important
    nis2.eu/sector: digital-provider
    nis2.eu/owner: doe25-group-13
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${PREFIX}adminer
  template:
    metadata:
      labels:
        app: ${PREFIX}adminer
    spec:
      containers:
      - name: ${PREFIX}adminer
        image: adminer:4.8.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20

---
