# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${PREFIX}mssql-sts
  namespace: doe25-group-13
  labels:
    app: ${PREFIX}mssql-sts
    nis2.eu/entity-classification: important
    nis2.eu/sector: digital-provider
    nis2.eu/owner: doe25-group-13
    nis2.eu/continuity-strategy: backup-restore
spec:
  selector:
    matchLabels:
      app: ${PREFIX}mssql-sts
  serviceName: "${PREFIX}mssql-sts"
  replicas: 1
  template:
    metadata:
      labels:
        app: ${PREFIX}mssql-sts
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ${PREFIX}mssql-sts
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
          name: mssql
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_PID
            value: "Developer"
          - name: MSSQL_SA_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mssql-secret
                key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      storageClassName: local-path
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
---

